/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanKu;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        time();
        
        controlPanel.removeAll();
        controlPanel.add(new dashboardPanel());
        controlPanel.revalidate();
        controlPanel.repaint();
    }

    void time(){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                labelTime.setText(dateFormat.format(new Date()));
            }
        });
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonDashboard = new javax.swing.JButton();
        buttonKategori = new javax.swing.JButton();
        buttonPeminjaman = new javax.swing.JButton();
        buttonDaftarBuku = new javax.swing.JButton();
        buttonKelolaAkun = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        buttonDaftarPeminjaman = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 83, 202));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-book-32.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PERBAKU");

        buttonDashboard.setBackground(new java.awt.Color(0, 83, 202));
        buttonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        buttonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-dashboard-24.png"))); // NOI18N
        buttonDashboard.setText("DASHBOARD");
        buttonDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        buttonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDashboard.setIconTextGap(10);
        buttonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDashboardActionPerformed(evt);
            }
        });

        buttonKategori.setBackground(new java.awt.Color(0, 83, 202));
        buttonKategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKategori.setForeground(new java.awt.Color(255, 255, 255));
        buttonKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-category-24.png"))); // NOI18N
        buttonKategori.setText("KATEGORI BUKU");
        buttonKategori.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        buttonKategori.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKategori.setIconTextGap(10);
        buttonKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKategoriActionPerformed(evt);
            }
        });

        buttonPeminjaman.setBackground(new java.awt.Color(0, 83, 202));
        buttonPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        buttonPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-note-24.png"))); // NOI18N
        buttonPeminjaman.setText("PEMINJAMAN");
        buttonPeminjaman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        buttonPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonPeminjaman.setIconTextGap(10);
        buttonPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPeminjamanActionPerformed(evt);
            }
        });

        buttonDaftarBuku.setBackground(new java.awt.Color(0, 83, 202));
        buttonDaftarBuku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDaftarBuku.setForeground(new java.awt.Color(255, 255, 255));
        buttonDaftarBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-book-24.png"))); // NOI18N
        buttonDaftarBuku.setText("DAFTAR BUKU");
        buttonDaftarBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        buttonDaftarBuku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDaftarBuku.setIconTextGap(10);
        buttonDaftarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftarBukuActionPerformed(evt);
            }
        });

        buttonKelolaAkun.setBackground(new java.awt.Color(0, 83, 202));
        buttonKelolaAkun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKelolaAkun.setForeground(new java.awt.Color(255, 255, 255));
        buttonKelolaAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-person-24.png"))); // NOI18N
        buttonKelolaAkun.setText("KELOLA USER");
        buttonKelolaAkun.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        buttonKelolaAkun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonKelolaAkun.setIconTextGap(10);
        buttonKelolaAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKelolaAkunActionPerformed(evt);
            }
        });

        buttonLogout.setBackground(new java.awt.Color(0, 83, 202));
        buttonLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-logout-24.png"))); // NOI18N
        buttonLogout.setText("LOGOUT");
        buttonLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        buttonLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonLogout.setIconTextGap(10);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        buttonDaftarPeminjaman.setBackground(new java.awt.Color(0, 83, 202));
        buttonDaftarPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonDaftarPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        buttonDaftarPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-detail-24.png"))); // NOI18N
        buttonDaftarPeminjaman.setText("DAFTAR PEMINJAMAN");
        buttonDaftarPeminjaman.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        buttonDaftarPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDaftarPeminjaman.setIconTextGap(10);
        buttonDaftarPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDaftarPeminjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonDaftarBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonKelolaAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonDaftarPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonDaftarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonDaftarPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonKelolaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 83, 202));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-close-32.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        labelTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTime.setForeground(new java.awt.Color(255, 255, 255));
        labelTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/latihanKu/image/icons8-dashboard2-24.png"))); // NOI18N
        labelTime.setText("0000-00-00 00:00:00");
        labelTime.setIconTextGap(10);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PERPUSTAKAAN BACA BUKU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(labelTime)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        controlPanel.setBackground(new java.awt.Color(234, 243, 255));
        controlPanel.setLayout(new java.awt.CardLayout(1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesOrNo == JOptionPane.YES_OPTION) {
            
        dispose();
        new loginFrame().setVisible(true);
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        int yesOrNo = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (yesOrNo == JOptionPane.YES_OPTION) {
            
        dispose();
        new loginFrame().setVisible(true);
        }
        
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDashboardActionPerformed
        // TODO add your handling code here:
        controlPanel.removeAll();
        controlPanel.add(new dashboardPanel());
        controlPanel.revalidate();
        controlPanel.repaint();
    }//GEN-LAST:event_buttonDashboardActionPerformed

    private void buttonKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKategoriActionPerformed
        // TODO add your handling code here:
        controlPanel.removeAll();
        controlPanel.add(new kategoriPanel());
        controlPanel.revalidate();
        controlPanel.repaint();
    }//GEN-LAST:event_buttonKategoriActionPerformed

    private void buttonDaftarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaftarBukuActionPerformed
        // TODO add your handling code here:
        controlPanel.removeAll();
        controlPanel.add(new bukuPanel());
        controlPanel.revalidate();
        controlPanel.repaint();
    }//GEN-LAST:event_buttonDaftarBukuActionPerformed

    private void buttonPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPeminjamanActionPerformed
        // TODO add your handling code here:
        controlPanel.removeAll();
        controlPanel.add(new pinjamPanel());
        controlPanel.revalidate();
        controlPanel.repaint();
    }//GEN-LAST:event_buttonPeminjamanActionPerformed

    private void buttonDaftarPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDaftarPeminjamanActionPerformed
        // TODO add your handling code here:
        controlPanel.removeAll();
        controlPanel.add(new detailPinjamPanel());
        controlPanel.revalidate();
        controlPanel.repaint();
    }//GEN-LAST:event_buttonDaftarPeminjamanActionPerformed

    private void buttonKelolaAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKelolaAkunActionPerformed
        // TODO add your handling code here:
        controlPanel.removeAll();
        controlPanel.add(new kelolaUserPanel());
        controlPanel.revalidate();
        controlPanel.repaint();
    }//GEN-LAST:event_buttonKelolaAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDaftarBuku;
    private javax.swing.JButton buttonDaftarPeminjaman;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JButton buttonKategori;
    private javax.swing.JButton buttonKelolaAkun;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonPeminjaman;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelTime;
    // End of variables declaration//GEN-END:variables
}
