/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package latihanKu;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class pinjamPanel extends javax.swing.JPanel {

    /**
     * Creates new form pinjamPanel
     */
    public pinjamPanel() {
        initComponents();
        
        auto_id();
        modelTabel();
        clear();
        clear2();
        nonEditable();
        tanggal();
    }
    
    
    void modelTabel(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID Buku");
        model.addColumn("Nama Buku");
        tablePinjam.setModel(model);
    }
    
    
    void tanggal(){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        txtTanggalPinjam.setText(dateFormat.format(date));
    }
    
    
    void load_data(){
        
        DefaultTableModel model = (DefaultTableModel) tablePinjam.getModel();
        String idBuku = txtIDBuku.getText();
        String namaBuku = txtNamaBuku.getText();
        
        Object[] data = {idBuku, namaBuku};
        
        model.addRow(data);
    }
    
    
    void nonEditable(){
        txtIDPinjam.setEditable(false);
        txtTanggalPinjam.setEditable(false);
        txtIDBuku.setEditable(false);
        txtNamaBuku.setEditable(false);
        txtTotalBuku.setEditable(false);
    }
    
    void clear(){
        
        txtIDBuku.setText(null);
        txtNamaBuku.setText(null);
    }
    
    void clear2(){
        txtNamaPeminjam.setText(null);
        JDateTanggalKembali.setDate(null);
        txtTotalBuku.setText("0");
    }
    
    
    void total(){
        DefaultTableModel model = (DefaultTableModel) tablePinjam.getModel();
        clear();
        txtTotalBuku.setText(String.valueOf(model.getRowCount()));
    }
    
    
    void emptyTable(){
        
        DefaultTableModel model = (DefaultTableModel) tablePinjam.getModel();
        
        while (model.getRowCount() > 0) {            
            model.removeRow(0);
        }
    }
    
    
    void reset(){
        txtNamaPeminjam.setText(null);
        txtIDBuku.setText(null);
        txtNamaBuku.setText(null);
        JDateTanggalKembali.setDate(null);
        emptyTable();
        txtTotalBuku.setText("0");
    }
    
    
    void auto_id(){
        
        try {
            String sql = "SELECT * FROM pinjam ORDER BY id_pinjam DESC";
            Connection cnVar = koneksi.getKoneksi();
            Statement stVar = cnVar.createStatement();
            ResultSet rsVar = stVar.executeQuery(sql);
            
            if (rsVar.next()) {
                String idPinjam = rsVar.getString("id_pinjam").substring(4);
                String valueIDPInjam = "" + (Integer.parseInt(idPinjam) + 1);
                String nol = "";
                
                if (valueIDPInjam.length() == 1) {
                    nol = "00000";
                } else if (valueIDPInjam.length() == 2) {
                    nol = "0000";
                } else if (valueIDPInjam.length() == 3) {
                    nol = "000";
                } else if (valueIDPInjam.length() == 4) {
                    nol = "00";
                } else if (valueIDPInjam.length() == 5) {
                    nol = "0";
                } else if (valueIDPInjam.length() == 6) {
                    nol = "";
                }     
                
                txtIDPinjam.setText("KDPJ" + nol + valueIDPInjam);
            } else {
                txtIDPinjam.setText("KDPJ000001");
            }
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, sQLException.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTanggalPinjam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIDPinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamaPeminjam = new javax.swing.JTextField();
        JDateTanggalKembali = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtIDBuku = new javax.swing.JTextField();
        txtNamaBuku = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePinjam = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        buttonCariBuku = new javax.swing.JButton();
        buttonLaporan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTotalBuku = new javax.swing.JTextField();
        buttonTambah = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonMuatUlang = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonCetak = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMINJAMAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TANGGAL PINJAM");

        txtTanggalPinjam.setBackground(new java.awt.Color(232, 232, 232));
        txtTanggalPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTanggalPinjam.setForeground(new java.awt.Color(0, 0, 0));
        txtTanggalPinjam.setText("jTextField1");
        txtTanggalPinjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID PINJAM");

        txtIDPinjam.setBackground(new java.awt.Color(232, 232, 232));
        txtIDPinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDPinjam.setForeground(new java.awt.Color(0, 0, 0));
        txtIDPinjam.setText("jTextField1");
        txtIDPinjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TANGGAL KEMBALI");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NAMA PEMINJAM");

        txtNamaPeminjam.setBackground(new java.awt.Color(232, 232, 232));
        txtNamaPeminjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamaPeminjam.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaPeminjam.setText("jTextField1");
        txtNamaPeminjam.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        JDateTanggalKembali.setBackground(new java.awt.Color(255, 255, 255));
        JDateTanggalKembali.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID BUKU");

        txtIDBuku.setBackground(new java.awt.Color(232, 232, 232));
        txtIDBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIDBuku.setForeground(new java.awt.Color(0, 0, 0));
        txtIDBuku.setText("jTextField1");
        txtIDBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        txtNamaBuku.setBackground(new java.awt.Color(232, 232, 232));
        txtNamaBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNamaBuku.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaBuku.setText("jTextField1");
        txtNamaBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NAMA BUKU");

        tablePinjam.setBackground(new java.awt.Color(255, 255, 255));
        tablePinjam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePinjam.setForeground(new java.awt.Color(0, 0, 0));
        tablePinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePinjam);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOMBOL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        buttonCariBuku.setBackground(new java.awt.Color(30, 144, 255));
        buttonCariBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCariBuku.setForeground(new java.awt.Color(255, 255, 255));
        buttonCariBuku.setText("CARI BUKU");
        buttonCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariBukuActionPerformed(evt);
            }
        });

        buttonLaporan.setBackground(new java.awt.Color(5, 90, 100));
        buttonLaporan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLaporan.setForeground(new java.awt.Color(255, 255, 255));
        buttonLaporan.setText("LAPORAN");
        buttonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(buttonCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TOTAL BUKU");

        txtTotalBuku.setBackground(new java.awt.Color(232, 232, 232));
        txtTotalBuku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalBuku.setForeground(new java.awt.Color(0, 0, 0));
        txtTotalBuku.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalBuku.setText("jTextField7");
        txtTotalBuku.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));

        buttonTambah.setBackground(new java.awt.Color(40, 167, 69));
        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setText("TAMBAH");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tombol Kelola", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        buttonMuatUlang.setBackground(new java.awt.Color(3, 169, 244));
        buttonMuatUlang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonMuatUlang.setForeground(new java.awt.Color(255, 255, 255));
        buttonMuatUlang.setText("MUAT ULANG");
        buttonMuatUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMuatUlangActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(244, 67, 54));
        buttonBatal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBatal.setForeground(new java.awt.Color(255, 255, 255));
        buttonBatal.setText("BATAL");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(40, 167, 69));
        buttonSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonCetak.setBackground(new java.awt.Color(5, 90, 100));
        buttonCetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCetak.setForeground(new java.awt.Color(255, 255, 255));
        buttonCetak.setText("CETAK");
        buttonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonMuatUlang))
                    .addComponent(buttonCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMuatUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(123, 123, 123)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(txtIDBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIDPinjam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(JDateTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(txtTotalBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIDPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDateTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotalBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariBukuActionPerformed
        // TODO add your handling code here:
        new dataBuku().setVisible(true);
    }//GEN-LAST:event_buttonCariBukuActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablePinjam.getModel();
        int choiceBaris = tablePinjam.getSelectedRow();
        
        if (choiceBaris > -1) {
            model.removeRow(choiceBaris);
            total();
        }  else {
            JOptionPane.showMessageDialog(null, "Harap memilih data yang ingin dihapus");
            return;
        }
        
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonMuatUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMuatUlangActionPerformed
        // TODO add your handling code here:
        reset();
        clear();
        auto_id();
        txtNamaPeminjam.setText("");
    }//GEN-LAST:event_buttonMuatUlangActionPerformed

    private void buttonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanActionPerformed
        // TODO add your handling code here:
        new laporanPinjam().setVisible(true);
    }//GEN-LAST:event_buttonLaporanActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        String idPinjam = txtIDPinjam.getText();
        String namaPeminjam = txtNamaPeminjam.getText();
        String tanggalPinjam = txtTanggalPinjam.getText();
        Date JDate = (Date) JDateTanggalKembali.getDate();
        int total = Integer.parseInt(txtTotalBuku.getText());
        
        if (idPinjam.isBlank() || namaPeminjam.isBlank() || tanggalPinjam.isBlank() || JDateTanggalKembali.getDate() == null || txtTotalBuku.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Harap mengisi data secara keseluruhan", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String tanggalKembali = new SimpleDateFormat("yyyy-MM-dd").format(JDate);
        
        if (tablePinjam.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Harap memilih buku untuk Peminjaman", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            Connection cnVar = koneksi.getKoneksi();
            String sqlCheck = "SELECT * FROM pinjam WHERE id_pinjam = ?";
            
            PreparedStatement psVar = cnVar.prepareStatement(sqlCheck);
            psVar.setString(1, idPinjam);
            ResultSet rsVar = psVar.executeQuery();
            
            if (rsVar.next()) {
                JOptionPane.showMessageDialog(null, "Peminjaman sudah dilakukan, harap Muat Ulang untuk membuat Peminjaman baru", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                
                String sqlPinjam = "INSERT INTO pinjam VALUES (?, ?, ?, ?, ?)";
                PreparedStatement psVarPinjam = cnVar.prepareStatement(sqlPinjam);
                
                psVarPinjam.setString(1, idPinjam);
                psVarPinjam.setString(2, namaPeminjam);
                psVarPinjam.setString(3, tanggalPinjam);
                psVarPinjam.setString(4, tanggalKembali);
                psVarPinjam.setInt(5, total);
                psVarPinjam.execute();
                psVarPinjam.close();
                
                String sqlDetailPinjam = "INSERT INTO detail_pinjam VALUES (?, ?, ?, ?)";
                PreparedStatement psVarDetailPinjam = cnVar.prepareStatement(sqlDetailPinjam);
                int jumlahData = tablePinjam.getRowCount();
                
                for (int i = 0; i < jumlahData; i++) {
                  
                    psVarDetailPinjam.setString(1, idPinjam);
                    psVarDetailPinjam.setString(2, tablePinjam.getValueAt(i, 0).toString());
                    psVarDetailPinjam.setString(3, tanggalPinjam);
                    psVarDetailPinjam.setString(4, tanggalKembali);
                    psVarDetailPinjam.execute();
                    
                }
                psVarDetailPinjam.close();
                
                JOptionPane.showMessageDialog(null, "Peminjaman berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, exception.getMessage());
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakActionPerformed
        // TODO add your handling code here:
        new cetakFrame().setVisible(true);
    }//GEN-LAST:event_buttonCetakActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        
        if (txtIDBuku.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Harap memilih data buku");
            return;
        } else {
            load_data();
            clear();
            total();
        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void tablePinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePinjamMouseClicked
        // TODO add your handling code here:
        int choicePoint = tablePinjam.rowAtPoint(evt.getPoint());
        
        String idBuku = tablePinjam.getValueAt(choicePoint, 0).toString();
        String namaBuku = tablePinjam.getValueAt(choicePoint, 1).toString();
        
        txtIDBuku.setText(idBuku);
        txtNamaBuku.setText(namaBuku);
    }//GEN-LAST:event_tablePinjamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateTanggalKembali;
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonCariBuku;
    private javax.swing.JButton buttonCetak;
    private javax.swing.JButton buttonLaporan;
    private javax.swing.JButton buttonMuatUlang;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePinjam;
    public static javax.swing.JTextField txtIDBuku;
    private javax.swing.JTextField txtIDPinjam;
    public static javax.swing.JTextField txtNamaBuku;
    private javax.swing.JTextField txtNamaPeminjam;
    private javax.swing.JTextField txtTanggalPinjam;
    private javax.swing.JTextField txtTotalBuku;
    // End of variables declaration//GEN-END:variables
}
